
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftIFFleftIMPLIESleftORleftANDrightNOTAND CONSTANT IFF IMPLIES LPAREN NOT OR RPAREN VARIABLEexpression : VARIABLEexpression : CONSTANTexpression : LPAREN expression RPARENexpression : NOT expressionexpression : expression AND expressionexpression : expression OR expressionexpression : expression IMPLIES expressionexpression : expression IFF expression'
    
_lr_action_items = {'VARIABLE':([0,4,5,6,7,8,9,],[2,2,2,2,2,2,2,]),'CONSTANT':([0,4,5,6,7,8,9,],[3,3,3,3,3,3,3,]),'LPAREN':([0,4,5,6,7,8,9,],[4,4,4,4,4,4,4,]),'NOT':([0,4,5,6,7,8,9,],[5,5,5,5,5,5,5,]),'$end':([1,2,3,11,12,13,14,15,16,],[0,-1,-2,-4,-5,-6,-7,-8,-3,]),'AND':([1,2,3,10,11,12,13,14,15,16,],[6,-1,-2,6,-4,-5,6,6,6,-3,]),'OR':([1,2,3,10,11,12,13,14,15,16,],[7,-1,-2,7,-4,-5,-6,7,7,-3,]),'IMPLIES':([1,2,3,10,11,12,13,14,15,16,],[8,-1,-2,8,-4,-5,-6,-7,8,-3,]),'IFF':([1,2,3,10,11,12,13,14,15,16,],[9,-1,-2,9,-4,-5,-6,-7,-8,-3,]),'RPAREN':([2,3,10,11,12,13,14,15,16,],[-1,-2,16,-4,-5,-6,-7,-8,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,5,6,7,8,9,],[1,10,11,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> VARIABLE','expression',1,'p_expression_variable','parse.py',32),
  ('expression -> CONSTANT','expression',1,'p_expression_constant','parse.py',36),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_paren','parse.py',40),
  ('expression -> NOT expression','expression',2,'p_expression_not','parse.py',44),
  ('expression -> expression AND expression','expression',3,'p_expression_and','parse.py',48),
  ('expression -> expression OR expression','expression',3,'p_expression_or','parse.py',52),
  ('expression -> expression IMPLIES expression','expression',3,'p_expression_implies','parse.py',56),
  ('expression -> expression IFF expression','expression',3,'p_expression_iff','parse.py',60),
]
