#include<stdio.h>
int main(){
putchar('|');
putchar('<');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('>');
putchar('|');
putchar('\n');
putchar('|');
printf("                           Elevator                      ");
putchar('|');
printf("                           Buildings                      ");
putchar('|');
putchar('\n');
putchar('|');
putchar('<');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('>');
putchar('|');
putchar('\n');
putchar('|');
printf("           States          ");
putchar('|');
printf("          PassStack          ");
putchar('|');
printf("            floor           ");
putchar('|');
printf("          PassQuene          ");
putchar('|');
putchar('\n');
putchar('|');
putchar('<');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('>');
putchar('|');
putchar('\n');
putchar('|');
printf("        StateBefore: %s    ","UK");
putchar('|');
printf("       destination0:  %d      ",5);
putchar('|');
printf("           Floor%d           ",0);
putchar('|');
printf("          Up: %d ,Down: %d     ",5,5);
putchar('|');
putchar('\n');
putchar('|');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('>');
putchar('|');
putchar('\n');
putchar('|');
printf("<------------------------->");
putchar('|');
printf("       destination0:  %d      ",5);
putchar('|');
printf("           Floor%d           ",0);
putchar('|');
printf("          Up: %d ,Down: %d     ",5,5);
putchar('|');
putchar('\n');
putchar('|');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('>');
putchar('|');
putchar('\n');
putchar('|');
printf("        StateBefore: %s    ","UK");
putchar('|');
printf("       destination0:  %d      ",5);
putchar('|');
printf("           Floor%d           ",0);
putchar('|');
printf("          Up: %d ,Down: %d     ",5,5);
putchar('|');
putchar('\n');
putchar('|');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar(' ');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('>');
putchar('|');
putchar('\n');
putchar('|');
printf("                           ");
putchar('|');
printf("       destination0:  %d      ",5);
putchar('|');
printf("           Floor%d           ",0);
putchar('|');
printf("          Up: %d ,Down: %d     ",5,5);
putchar('|');
putchar('\n');
putchar('|');
putchar('<');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('>');
putchar('|');
putchar('\n');
putchar('|');
printf("        StateBefore: %s    ","UK");
putchar('|');
printf("       destination0:  %d      ",5);
putchar('|');
printf("           Floor%d           ",0);
putchar('|');
printf("          Up: %d ,Down: %d     ",5,5);
putchar('|');
putchar('\n');
putchar('|');
putchar('<');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('-');
putchar('>');
putchar('|');
putchar('\n');





   
    return 1;

}