include $(SRC_RT)/myOS/kernel/mem/Makefile
include $(SRC_RT)/myOS/kernel/task/Makefile
include $(SRC_RT)/myOS/kernel/time/Makefile

KERNEL_OBJS = 	$(TIME_OBJS) \
				$(TASK_OBJS)  \
 	      		$(MEM_OBJS) 
