TASK_OBJS =	output/myOS/kernel/task/scheduler.o \
 		output/myOS/kernel/task/task.o\
		output/myOS/kernel/task/taskArrv.o \
		output/myOS/kernel/task/taskPara.o \
		output/myOS/kernel/task/taskQueue.o